theme: minima
title: 2020 NC Voter Registrations
author:
  name:  'Buro Mookerji'
timezone: UTC−07:00
header_pages:
- about.md
- demographics.md
- counties.md
- vote.md
plugins:
- jekyll-seo-tag
google_analytics: UA-13296601-2
