version: 2.1
jobs:
  fetch_build:
    docker:
    - image: cimg/python:3.8.5
    steps:
    - checkout
    - run: python --version
    - run: pip3 install -r requirements.txt
    - run: mkdir -p limbo/
    - run: bash scripts/fetch.sh
    - run: bash scripts/make-data.sh

workflows:
  version: 2
  commit:
    jobs:
      - fetch_build:
          filters:
            branches:
              only:
                - master
  nightly:
    triggers:
    - schedule:
        cron: "0 * * * *"
        filters:
          branches:
            only:
            - master
    jobs:
    - fetch_build
